<?php

function securitydemo_menu() {
  $items = array();
  
  $items['insecure-node/%node'] = array(
    'title callback' => 'securitydemo_node_title',
    'title arguments' => array(1),
    'page callback' => 'securitydemo_node_body',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function securitydemo_node_title($node) {
  return $node->title;
}

function securitydemo_node_body($node) {
  return $node->body[LANGUAGE_NONE][0]['safe_value'];
}