<?php

function securitydemo_menu() {
  $items = array();
  
  $items['insecure-node/%node'] = array(
    'title callback' => 'securitydemo_node_title',
    'title arguments' => array(1),
    'page callback' => 'securitydemo_node_body',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );
  
  return $items;
}

function securitydemo_node_title($node) {
  return $node->title;
}

function securitydemo_node_body($node) {
  $title = t('Title: @title', array('@title' => $node->title));
  $body = $node->body[LANGUAGE_NONE][0]['safe_value'];
  
  $revision_log = $node->log;
  dpm($node);
  return '<h2>' . $title . '</h2>' . $body . '<div>Revision Log: ' . filter_xss($revision_log) . '</div>';
}

function securitydemo_node_presave($node) {
  db_query("INSERT INTO {securitydemo} (log) VALUES (:message)", 
    array(':message' => $node->title));
}