<?php



/**
 * Implementation of hook_user_load().
 * 
 * @param type $users
 */
function userhooks_user_load($users) {
  foreach ($users as $uid => $user) {
    $users[$uid]->userhooks_name = __userhooks_translate_to_pig_latin(strtolower($user->name));
  }
//  dpm($users);
}

/**
 * Implementation of hook_user_view().
 * 
 * @param type $account
 * @param type $view_mode
 * @param type $langcode
 */
function userhooks_user_view($account, $view_mode, $langcode) {
  if ($view_mode == 'full' && !empty($account->userhooks_name)) {
    $account->content['userhooks'] = array(
      '#markup' => '<dl><dt>' . t('Pig Latin Name') . '</dt><dd>' . $account->userhooks_name . '</dd></dl>',
      '#weight' => 100,
    );
  }
}

/**
 * Implementation of hook_user_presave().
 * 
 * @param type $edit
 * @param type $account
 * @param type $category
 */
function userhooks_user_presave(&$edit, $account, $category) {
  watchdog('userhooks', "I'm about save user @user.", array('@user' => $account->name));
}

/**
 * Implementation of hook_user_insert().
 * 
 * @param type $edit
 * @param type $account
 * @param type $category
 */
function userhooks_user_insert(&$edit, $account, $category) {
  watchdog('userhooks', "@logged_in_user created user @user.", 
    array('@logged_in_user' => $GLOBALS['user']->name, '@user' => $account->name));
}

/**
 * Implementation of hook_user_update().
 * 
 * @param type $edit
 * @param type $account
 * @param type $category
 */
function userhooks_user_update(&$edit, $account, $category) {
  watchdog('userhooks', "@logged_in_user updated user @user.", 
    array('@logged_in_user' => $GLOBALS['user']->name, '@user' => $account->name));
}

/**
 * Implementation of hook_user_delete().
 * 
 * @param type $edit
 * @param type $account
 * @param type $category
 */
function userhooks_user_delete($account) {
  drupal_set_message(t("Oh! I'm melting! Melting! Oh, what a world! What a world!"), 'warning');
}

/**
 * Implementation of hook_user_login().
 * 
 * @param type $edit
 * @param type $account
 */
function userhooks_user_login(&$edit, $account) {
  drupal_set_message(t("Howdy, @user!", array('@user'=> $account->name)));
}

/**
 * Implementation of hook_user_logout().
 * 
 * @param type $account
 */
function userhooks_user_logout($account) {
  if ($account->name == 'dave') {
    drupal_set_message(t("I'm sorry Dave. I'm afraid I can't let you do that."), 'error');
    drupal_goto('<front>');
  }
}





/**
 * Translate strings to Pig Latin.
 * 
 * @param type $string
 * @return type
 */
function __userhooks_translate_to_pig_latin($string) {
  $words = explode(' ', $string);
  $pig_latin = array();
  foreach ($words as $word) {
    if (in_array(strtolower(substr($word, 0, 1)), array('a', 'e', 'i', 'o', 'y'))) {
      $pig_latin[] =  $word . 'way';
    }
    else {
      $pig_latin[] = substr($word, 1) . substr($word, 0, 1) . 'ay';
    }
        
  }
  return implode(' ', $pig_latin);
}