<?php

function hello_menu_menu() {
  $items = array();
  
  $items['hello'] = array(
    'title' => 'Hello World',
    'description' => 'This is where say hello!',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => array('access content'),
    'menu_name' => 'main-menu',
    'weight' => 1,
  );
  
  $items['hello/simple'] = array(
    'title' => 'Simple',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );
  
  $items['hello/variables'] = array(
    'title' => 'Hello Variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['hello/variables/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  $items['hello/variables/create'] = array(
    'title' => 'Create Variable',
    'page callback' => 'hello_menu_create_variable',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  
  $items['hello/variables/delete'] = array(
    'title' => 'Delete Variable',
    'page callback' => 'hello_menu_delete_variable',
    'access arguments' => array('access content'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  
  
  $items['hello/variables/%'] = array(
    'title callback' => 'hello_menu_show_variable_title',
    'title arguments' => array(2),
    'page callback' => 'hello_menu_show_variable',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

function hello_menu_delete_variable() {
  return t('This is where we delete variables.');
}

function hello_menu_create_variable() {
  return t('This is where we create variables.');
}

function hello_menu_show_variable_title($variable_name) {
  return t('Show Variable: @name', array('@name' => $variable_name));
}

function hello_menu_show_variable($variable_name) {
  $value = variable_get($variable_name, t('No value for this variable.'));
  return (string) $value;
}

function hello_menu_list_variables() {
  $variables = variable_initialize();
  $names = array_keys($variables);
  $output = '<ul>';
  
  foreach ($names as $name) {
    $output .= '<li>' . l($name, 'hello/variables/' . $name, array('attributes' => array('class' => array('test-link', 'other-link')))) . '</li>';
  }
  
  $output .= '</ul>';
  return $output;
}

function hello_menu_simple_hello() {
  return t('Hello world!!');
}