<?php


function hamsters_menu() {
  $items = array();
  
  $items['hamsters'] = array(
    'title' => 'Hamsters',
    'page callback' => 'hamsters_list',
    'access arguments' => array('view hamsters'),
  );
  
  return $items;
}

function hamsters_list() {
  $output = '';
  $header = array(
    t('ID'),
    t('Name'),
    t('Gender'),
    t('Weight'),
    t('Birth Date'),
    t('Image'),
    t('Habitat'),
  );
  $rows = array();
  
  $results = db_query("SELECT h.*, hh.name as habitat_name FROM {hamsters} h
                       LEFT JOIN {hamsters_habitat} hh ON h.habitat_id = hh.id");
  
  foreach ($results as $record) {
    $row = array(
      $record->id,
      $record->name,
      $record->gender,
      t('@weight g', array('@weight' => $record->weight)),
      format_date($record->birthdate, 'custom', 'm/d/Y'),
      theme('image', array('path' => file_build_uri($record->image))),
      $record->habitat_name,
    );
    $rows[] = $row;
  }
  $output .= theme('table', array('header' => $header, 'rows' => $rows));
  
  return $output;
}

function hamsters_permission() {
  return array(
    'view hamsters' => array(
      'title' => t('View Hamsters'),
      'description' => t('View information about hamsters in the database.'),
    ),
  );
}