<?php

/**
 * Implements hook_node_load()
 * 
 * @param type $nodes
 * @param type $types
 */
function nodehooks_node_load($nodes, $types) {
  // Add pig-latin title to all article nodes
  if (in_array('article', $types)) {
    foreach ($nodes as $nid => $node) {
      $nodes[$nid]->nodehooks_title = ucfirst(__nodehooks_translate_to_pig_latin(strtolower($node->title)));
    }
  }
  // dpm($nodes);
  // dpm($types);
}

/**
 * Implementation of hook_node_view().
 * 
 * @param type $node
 * @param type $view_mode
 * @param type $langcode
 */
function nodehooks_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && !empty($node->nodehooks_title)) {
    $node->content['nodehooks'] = array(
      '#markup' => '<div class="nodehooks"><strong>' . t('Pig Latin Title') . ':</strong> ' . $node->nodehooks_title . '</div>',
      '#weight' => 100,
    );
  }
}

/**
 * Implementation of hook_node_validate().
 * 
 * @param type $node
 * @param type $form
 * @param type $form_state
 */
function nodehooks_node_validate($node, $form, &$form_state) {
  if (strstr(strtolower($form_state['values']['title']), 'fight club')) {
    form_set_error('title', t("The first rule of Fight Club: Don't talk about Fight Club."));
  }
}

/**
 * Implementation of hook_node_submit().
 * 
 * @param type $node
 * @param type $form
 * @param type $form_state
 */
function nodehooks_node_submit($node, $form, &$form_state) {
  if ($node->type == 'article') {
    drupal_set_message(t('Your article, %title, will be reviewed by an editor soon.', array('%title' => $node->title)), 'warning');
  }
}

/**
 * Implementation of hook_node_presave().
 * 
 * @param type $node
 */
function nodehooks_node_presave($node) {
  $node->body[LANGUAGE_NONE][0]['value'] = str_replace('Voldemort', 'He who must not be named', $node->body[LANGUAGE_NONE][0]['value']);
}

/**
 * Implementation of hook_node_insert().
 * 
 * @param type $node
 */
function nodehooks_node_insert($node) {
  if ($node->type == 'article') {
    watchdog('nodehooks', 'Article %title created by !user.', 
      array('%title' => $node->title, '!user' => l($node->name, 'user/' . $node->uid)));
  }
}

/**
 * Implementation of hook_node_update().
 * 
 * @param type $node
 */
function nodehooks_node_update($node) {
  if ($node->type == 'article') {
    watchdog('nodehooks', 'Article %title updated.', array('%title' => $node->title));
  }
}

/** 
 * Implementation of hook_node_delete().
 * 
 * @param type $node
 */
function nodehooks_node_delete($node) {
  if ($node->type == 'article') {
    drupal_set_message(t('Ouch! That hurts.'), 'warning');
  }
}



/**
 * Translate strings to Pig Latin.
 * 
 * @param type $string
 * @return type
 */
function __nodehooks_translate_to_pig_latin($string) {
  $words = explode(' ', $string);
  $pig_latin = array();
  foreach ($words as $word) {
    if (in_array(strtolower(substr($word, 0, 1)), array('a', 'e', 'i', 'o', 'y'))) {
      $pig_latin[] =  $word . 'way';
    }
    else {
      $pig_latin[] = substr($word, 1) . substr($word, 0, 1) . 'ay';
    }
        
  }
  return implode(' ', $pig_latin);
}